/**
 * styles.ts — Visual style presets for the template combinator.
 * Each preset defines theme colors, fonts, and radius.
 * Combined with niche content to create unique templates.
 */

import type { Theme } from "@/lib/schema/page-schema";

export interface StylePreset {
  id: string;
  name: string;
  theme: Omit<Theme, "density">;
}

/** 11 visual styles × ~100 niches = 2001+ templates. */
export const STYLE_PRESETS: StylePreset[] = [
  {
    id: "minimal-light",
    name: "Minimal Light",
    theme: {
      mode: "light",
      radius: "sm",
      fonts: { heading: "DM Sans", body: "Inter" },
      colors: {
        background: "#FFFFFF",
        foreground: "#0a0a0b",
        primary: "#0a0a0b",
        primaryForeground: "#FFFFFF",
        secondary: "#f4f4f5",
        accent: "#6b7280",
        muted: "#f9fafb",
        mutedForeground: "#6b7280",
        border: "#e5e7eb",
        card: "#FFFFFF",
        cardForeground: "#0a0a0b",
      },
    },
  },
  {
    id: "minimal-dark",
    name: "Minimal Dark",
    theme: {
      mode: "dark",
      radius: "sm",
      fonts: { heading: "DM Sans", body: "Inter" },
      colors: {
        background: "#09090b",
        foreground: "#fafafa",
        primary: "#fafafa",
        primaryForeground: "#09090b",
        secondary: "#1c1c1e",
        accent: "#a1a1aa",
        muted: "#18181b",
        mutedForeground: "#a1a1aa",
        border: "#27272a",
        card: "#111113",
        cardForeground: "#fafafa",
      },
    },
  },
  {
    id: "bold-indigo",
    name: "Bold Indigo",
    theme: {
      mode: "dark",
      radius: "md",
      fonts: { heading: "Space Grotesk", body: "Inter" },
      colors: {
        background: "#0f0f1a",
        foreground: "#eef0ff",
        primary: "#6366f1",
        primaryForeground: "#FFFFFF",
        secondary: "#1e1b4b",
        accent: "#818cf8",
        muted: "#1a1a2e",
        mutedForeground: "#9ca3af",
        border: "#312e81",
        card: "#151528",
        cardForeground: "#eef0ff",
      },
    },
  },
  {
    id: "warm-elegant",
    name: "Warm Elegant",
    theme: {
      mode: "light",
      radius: "sm",
      fonts: { heading: "Playfair Display", body: "Lora" },
      colors: {
        background: "#FFFDF7",
        foreground: "#292524",
        primary: "#92400e",
        primaryForeground: "#FFFFFF",
        secondary: "#fef3c7",
        accent: "#d97706",
        muted: "#faf5ee",
        mutedForeground: "#78716c",
        border: "#e7e0d5",
        card: "#FFFDF7",
        cardForeground: "#292524",
      },
    },
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    theme: {
      mode: "dark",
      radius: "none",
      fonts: { heading: "Playfair Display", body: "Lora" },
      colors: {
        background: "#0c0a09",
        foreground: "#f5f0e8",
        primary: "#c9a96e",
        primaryForeground: "#0c0a09",
        secondary: "#1c1917",
        accent: "#8b7355",
        muted: "#1a1816",
        mutedForeground: "#a8a29e",
        border: "#2c2520",
        card: "#121110",
        cardForeground: "#f5f0e8",
      },
    },
  },
  {
    id: "fresh-green",
    name: "Fresh Green",
    theme: {
      mode: "light",
      radius: "lg",
      fonts: { heading: "DM Serif Display", body: "Nunito Sans" },
      colors: {
        background: "#f0fdf4",
        foreground: "#14532d",
        primary: "#15803d",
        primaryForeground: "#FFFFFF",
        secondary: "#dcfce7",
        accent: "#4ade80",
        muted: "#ecfdf5",
        mutedForeground: "#6b7280",
        border: "#bbf7d0",
        card: "#f0fdf4",
        cardForeground: "#14532d",
      },
    },
  },
  {
    id: "vibrant-pink",
    name: "Vibrant Pink",
    theme: {
      mode: "light",
      radius: "xl",
      fonts: { heading: "Quicksand", body: "Nunito" },
      colors: {
        background: "#FFFFFF",
        foreground: "#1f2937",
        primary: "#ec4899",
        primaryForeground: "#FFFFFF",
        secondary: "#fce7f3",
        accent: "#f472b6",
        muted: "#fdf2f8",
        mutedForeground: "#6b7280",
        border: "#fbcfe8",
        card: "#FFFFFF",
        cardForeground: "#1f2937",
      },
    },
  },
  {
    id: "tech-neon",
    name: "Tech Neon",
    theme: {
      mode: "dark",
      radius: "sm",
      fonts: { heading: "JetBrains Mono", body: "Inter" },
      colors: {
        background: "#030712",
        foreground: "#d1fae5",
        primary: "#22c55e",
        primaryForeground: "#030712",
        secondary: "#0f1a14",
        accent: "#4ade80",
        muted: "#111827",
        mutedForeground: "#9ca3af",
        border: "#1f3a2a",
        card: "#0a1210",
        cardForeground: "#d1fae5",
      },
    },
  },
  {
    id: "ocean-calm",
    name: "Ocean Calm",
    theme: {
      mode: "light",
      radius: "lg",
      fonts: { heading: "Poppins", body: "Inter" },
      colors: {
        background: "#f0f9ff",
        foreground: "#0c4a6e",
        primary: "#0ea5e9",
        primaryForeground: "#FFFFFF",
        secondary: "#e0f2fe",
        accent: "#38bdf8",
        muted: "#f0f9ff",
        mutedForeground: "#6b7280",
        border: "#bae6fd",
        card: "#f0f9ff",
        cardForeground: "#0c4a6e",
      },
    },
  },
  {
    id: "fire-energy",
    name: "Fire Energy",
    theme: {
      mode: "dark",
      radius: "sm",
      fonts: { heading: "Oswald", body: "Source Sans 3" },
      colors: {
        background: "#0c0404",
        foreground: "#fef2f2",
        primary: "#dc2626",
        primaryForeground: "#FFFFFF",
        secondary: "#1c0a0a",
        accent: "#ef4444",
        muted: "#1a0f0f",
        mutedForeground: "#a1a1aa",
        border: "#3b1010",
        card: "#120808",
        cardForeground: "#fef2f2",
      },
    },
  },
  {
    id: "purple-premium",
    name: "Purple Premium",
    theme: {
      mode: "dark",
      radius: "md",
      fonts: { heading: "Plus Jakarta Sans", body: "Inter" },
      colors: {
        background: "#0a0514",
        foreground: "#f3f0ff",
        primary: "#7c3aed",
        primaryForeground: "#FFFFFF",
        secondary: "#1e1040",
        accent: "#a78bfa",
        muted: "#150d28",
        mutedForeground: "#9ca3af",
        border: "#2e1a5e",
        card: "#110a20",
        cardForeground: "#f3f0ff",
      },
    },
  },
];
